AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  function-sample-aws

  サンプル

Globals:
  Function:
    Timeout: 20

Resources:
  MyFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: .
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      Runtime: java11
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: "rate(5 minutes)"
            Name: TestSchedule
            Description: test schedule
      MemorySize: 512
      Environment:
        Variables:
          MAIN_CLASS: example.FunctionConfiguration
      Tracing: Active

Outputs:
  MyFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt MyFunction.Arn
  MyFunctionIamRole:
    Description: "Implicit IAM Role"
    Value: !GetAtt MyFunctionRole.Arn
